- hosts: balancers
  become: yes
  
  tasks:
    # usage: ansible-playbook playbooks/exclude_backend.yml -e "backend_name=app1 backend_state=disabled"
    - name: "{{ backend_state }} the backend server in HAProxy."
      haproxy:
        state: "{{ backend_state }}"
        host: '{{ backend_name }}'
        socket: /var/lib/haproxy/stats
        backend: habackend
