- name: Setup awx server and cli then creates AWX jobs and other ressources
  hosts: localhost

  collections: #ensure to have awx collection installed : ansible-galaxy collection install awx.awx
    - awx.awx

  vars:
    awx_cli_host: "http://10.10.10.131"
    awx_cli_username: admin
    awx_cli_password: "unsecurepass"

  tasks:
    - name: Ensure AWX cli installed
      pip:
        name: https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-3.8.1-1.tar.gz
        executable: pip3
      become: yes

    - name: Ensure Orga AWX orga exists 
      tower_organization:
        tower_host: "{{ awx_cli_host }}"
        tower_username: "{{ awx_cli_username }}"
        tower_password: "{{ awx_cli_password }}"
        name: Orga
        galaxy_credentials:
          - Ansible Galaxy
        state: present


    - name: Ensure TP4 project exists
      tower_project:
        tower_host: "{{ awx_cli_host }}"
        tower_username: "{{ awx_cli_username }}"
        tower_password: "{{ awx_cli_password }}"
        name: TP4
        organization: Orga
        scm_url: https://github.com/e-lie/ansible_tp_corrections.git
        scm_type: git
        scm_branch: tp4_correction
        scm_clean: yes
        scm_update_on_launch: yes
        scm_update_cache_timeout: 0
        wait: yes
        state: present

    - name: Ensure ssh key credential exists
      tower_credential:
        tower_host: "{{ awx_cli_host }}"
        tower_username: "{{ awx_cli_username }}"
        tower_password: "{{ awx_cli_password }}"
        name: id_stagiaire
        organization: Orga
        credential_type: Machine
        inputs:
          ssh_key_data: dummy #edit value in AWX webui later 
          ssh_key_unlock: "devops101"
        state: present
      changed_when: False # due to encrypted data the tasks returns always changed status -> silent this 

    - name: Ensure inventory exists
      tower_inventory:
        tower_host: "{{ awx_cli_host }}"
        tower_username: "{{ awx_cli_username }}"
        tower_password: "{{ awx_cli_password }}"
        name: inventory.cfg
        organization: Orga
        variables:
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: stagiaire
        state: present

    - name: Ensure inventory file source exists
      tower_inventory_source:
        tower_host: "{{ awx_cli_host }}"
        tower_username: "{{ awx_cli_username }}"
        tower_password: "{{ awx_cli_password }}"
        name: "file inventory.cfg"
        inventory: inventory.cfg
        source: scm
        source_project: TP4
        source_path: inventory.cfg
        overwrite: yes
        update_on_project_update: yes
        verbosity: 1
        state: present

    - name: Ensure global configuration playbook template exists
      tower_job_template:
        tower_host: "{{ awx_cli_host }}"
        tower_username: "{{ awx_cli_username }}"
        tower_password: "{{ awx_cli_password }}"
        name: "Global Config"
        organization: Orga
        job_type: "run"
        inventory: "inventory.cfg"
        project: "TP4"
        playbook: "site.yml"
        credentials:
          - "id_stagiaire"
        state: present

